 title                 : Alp Karaagac
 email                 : 
 description: >- 
   Personal blog and portfolio - AI, ML, NLP and beyond
 baseurl               : ""
 url                   : http://alpkaraagac.github.io
 github_username       : AlpKaraagac
    
 remote_theme          : mmistakes/minimal-mistakes
 minimal_mistakes_skin : default
 search                : true
 words_per_minute      : 200
    
 markdown              : kramdown
 highlighter           : rouge
 permalink             : /:categories/:title/
 paginate              : 5
 paginate_path         : /page:num/
 timezone              : Europe/Berlin
    
 teaser: /assets/images/default/teaserfallback.png
 logo: /assets/images/default/logo.png
    
 include:
   - _pages
   - _posts
      
 plugins:
   - jekyll-feed
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-gist
   - jekyll-feed
   - jemoji
   - jekyll-include-cache
    
 author:
  name      : "Alp Karaagac"
  avatar    : "/assets/images/default/bio-photo.jpg"
  bio       : "That's me!"
  location  : "Munich, Germany"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AlpKaraagac"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/alpkaraagac"

    
 footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AlpKaraagac"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/alpkaraagac"

    
 encoding             : "utf-8"

 category_archive:
   type: liquid
   path: /categories/
 tag_archive:
   type: liquid
   path: /tags/
    
 defaults:
   - scope:
       path: ""
       type: posts
     values:
       layout: single
       author_profile: true
       read_time: true
       related: true
       show_date: true
   - scope:
       path: "_pages"
       type: pages
     values:
       layout: single
       author_profile: true