 title                 : Your awesome blog
 email                 : 
 description: >- 
   Some description.
 baseurl               : ""
 url                   : http://yourname.github.io
 github_username       : annjulyleon
    
 remote_theme          : mmistakes/minimal-mistakes
 minimal_mistakes_skin : default
 search                : true
 words_per_minute      : 200
    
 markdown              : kramdown
 highlighter           : rouge
 permalink             : /:categories/:title/
 paginate              : 5
 paginate_path         : /page:num/
 timezone              : Europe/Moscow
    
 teaser: /assets/images/default/teaserfallback.png
 logo: /assets/images/default/logo.png
    
 include:
   - _pages
      
 plugins:
   - jekyll-feed
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-gist
   - jekyll-feed
   - jemoji
   - jekyll-include-cache
    
 author:
   name                : "Your Name"
   avatar              : "/assets/images/default/bio-photo.jpg"
   bio                 : "That's me!"
   location            : "Moscow, Russia"
   links:
     - label: "GitHub"
       icon: "fab fa-fw fa-github"
       url: "https://github.com/yourname"
     - label: "LinkdIn"
       icon: "fab fa-fw fa-linkedin"
       url: "https://www.linkedin.com/in/yourname/"
    
 footer:
   links:
     - label: "GH"
       icon: "fab fa-fw fa-github"
       url: "https://github.com/yourname"
     - label: "LI"
       icon: "fab fa-fw fa-linkedin"
       url: "https://www.linkedin.com/in/yourname/"
    
 encoding             : "utf-8"
     
 category_archive:
   type: liquid
   path: /categories/
 tag_archive:
   type: liquid
   path: /tags/
    
 defaults:
   - scope:
       path: ""
       type: posts
     values:
       layout: single
       author_profile: true
       read_time: true
       related: true
       show_date: true
   - scope:
       path: "_pages"
       type: pages
     values:
       layout: single
       author_profile: true